### ISSUE TITLE
Attempt to send mail as authenticated user results in "451 Unable allocate descriptor to store message"

### ISSUE THREAD

**Issue by theyoyojo** [underground-software/orbit#43]
This is generated by either line 530 or 537 of smtp.c

**Comment by charliemirabile** [comment]
docker filesystem is basically read only unless we mount a volume for storing the data. We will also run into the upstream bug with linkat I am trying to get fixed if we try and run the email stuff in a container

**Comment by theyoyojo** [comment]
https://github.com/underground-software/syzygy/releases/tag/v0.1
