### ISSUE TITLE
Some backup scripts are outdated

### ISSUE THREAD

**Issue by erer1243** [underground-software/orbit#55]
Some backup scripts are outdated now, at the least because they use the old /var/orbit project root instead of the dockerized /orbit. 

My approach to fixing them would be to separate important files into a docker volume (this should be done anyway for basic persistence) and then update the backup scripts so they can be run autonomously from within a/the docker container.

**Comment by theyoyojo** [comment]
interesting, good idea

**Comment by theyoyojo** [comment]
See https://github.com/underground-software/singularity/issues/15
